title: El mejor juego de la historia
description:  Aprende casi todo, quiero decir todo sobre PVZ GW2. DISFRUTA, o no...
permalink: ':title/'
baseurl: "/" 
url: "https://elmejorjuegodelahistoria.github.io" 
site-twitter: 


author: Dave el loco ft. Doctor Zombie
author-img: pvz.jpg
about-author: Aqui las plantas y los zombies dejamos nuestras diferencias y cerebroz y trabajamos en cooperativo.
social-twitter: 
social-facebook: 
social-github: 
social-linkedin: 
social-email: 




# Disqus
discus-identifier:  

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
